[package]
name = "xmss-types"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true, default-features = false, features = ["derive"] }

[features]
default = ["std"]
std = ["serde/std"]